---
title: "Lösungen der Übungsaufgaben"
author: "Doga Ceren Bozkurt-Sezin Özer"
date: "2024-11-24"
output: html_document
---

```{r}
# Installiere und lade das Paket MKpower
install.packages("MKpower")
library(MKpower)
```

```{r}
# Prävalenz 2.5%
result_025 <- ssize.propCI(prop = 0.025, width= 0.02,  method = "wald-cc")
print(result_025)

# Prävalenz 3%
result_03 <- ssize.propCI(prop = 0.03, width = 0.03 ,  method = "wald-cc")
print(result_03)

# Prävalenz 3.5%
result_035 <- ssize.propCI(prop = 0.035, width =0.04,  method = "wald-cc")
print(result_035)

# Prävalenz 4%
result_04 <- ssize.propCI(prop = 0.04, width = 0.05,  method = "wald-cc")
print(result_04)

# Prävalenz 4.5%
result_045 <- ssize.propCI(prop = 0.045, width = 0.02, method = "wald-cc")
print(result_045)
```




# Prävalenz 3%
result_03 <- ssize.propCI(prop = 0.03, width = 0.03 , method = "wald-cc")
print(result_03)
mit diesen Werten kommt man zu dem gewünschten Ergebnis.
 Sample size calculation by method of wald-cc

              n = 561.5166
           prop = 0.03
          width = 0.03
     conf.level = 0.95