# ITSDaten einlesen aus der CSV-Datei
ITSDaten_Gruppe3_MTZ <- read.csv2(file = "ITSDaten_Gruppe3_MTZ.csv", fileEncoding = "utf-8", stringsAsFactors = TRUE)

# Verteilung der Leberversagen-Werte in der Tabelle berechnen
leberversagen_verteilung <- table(ITSDaten_Gruppe3_MTZ$Leberversagen) / nrow(ITSDaten_Gruppe3_MTZ)

# Ausgabe der Verteilung
print(leberversagen_verteilung)
-


# CSV-Datei einlesen
ITSDaten_Gruppe3_MTZ <- read.csv2(file = "ITSDaten_Gruppe3_MTZ.csv", fileEncoding = "utf-8", stringsAsFactors = TRUE)

# Filtern der Daten für Patienten mit einer Aufenthaltsdauer von genau einem Tag (LOS = 1)
ITSDaten_LOS1 <- ITSDaten_Gruppe3_MTZ[ITSDaten_Gruppe3_MTZ$LOS == 1, ]

# Entfernen des Ausreißers mit einer Körpertemperatur von 9,1 Celsius
ITSDaten_LOS1 <- ITSDaten_LOS1[ITSDaten_LOS1$Temperatur > 10, ]


# Ausgabe der bereinigten Daten
print(ITSDaten_LOS1)




ITSDaten_ML_Schätzer <- fitdistr(ITSDaten_LOS1$Temperatur, densfun = "normal")

# Ausgabe der Ergebnisse
print(ITSDaten_ML_Schätzer)



# Maximale Körpertemperatur extrahieren
temperatur <- ITSDaten_ML_Schätzer$Temperatur

# ML-Schätzer berechnen
ml_mean <- mean(temperatur)
ml_sd <- sd(temperatur)



# Median berechnen
median_temperatur <- median(temperatur)

# MAD berechnen
mad_temperatur <- mad(temperatur)
print(median_temperatur)
print(mad_temperatur)
